### ISSUE TITLE
Issue with images loading

### ISSUE THREAD

**Issue by ptgoldberg** [CodingDojo-MEAN-01-19/paulg#1]
Hi Jason, I can't figure out why the images won't load while using EJS to render the html for the EJS cars and cats

**Comment by dojo-json** [comment]
It appears you currently have images in your template directory. Only `ejs` templates should reside in views. Move your images to your static directory, along with your stylesheets directory. Now that your static content is all in the same place you can have express serve it with little input from you.

In your `server.js` add the following above your routes.

```javascript
app.use(express.static(path.join(__dirname, 'static')));
```

Now express will examine that directory for any static assets requested by a client.

Throw a quick `console.log` in your root route. Are requests reaching that point anymore?

Consider why this is.

**Comment by dojo-json** [comment]
Did this suggestion help? If so you can close this issue with your next push by adding `resolves #1` in your commit message. Check [here](https://help.github.com/articles/closing-issues-using-keywords/) for more info.
